import type { Metadata } from "next";
import { Inter as FontSans } from "next/font/google"
import "./globals.css";
import Navbar from "./components/Navbar";
import { cn } from "@/lib/utils"
 
const fontSans = FontSans({
  subsets: ["latin"],
  variable: "--font-sans",
})

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={cn(
          "min-h-screen bg-amber-100 font-sans antialiased",
          fontSans.variable
        )}>
        <Navbar />
        <div className="mx-auto w-10/12 px-4 sm:px-6 lg:px-8">
          { children }
        </div>
      </body>
    </html>
  );
}
